version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data: